name: Waka Readme

on:
  schedule:
    # Runs at 21:30 KST
    - cron: '20 12 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README with WakaTime stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "en"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "False"
          SHOW_PROJECTS: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
